.IFJcode22
DEFVAR GF@tmpPrint
DEFVAR GF@tmpRead
CREATEFRAME
PUSHFRAME
DEFVAR LF@test
PUSHS int@53
POPS LF@test
PUSHS LF@test
READ GF@tmpRead int
PUSHS GF@tmpRead
LTS
PUSHs bool@true
JUMPIFNEQS ower%2
PUSHS LF@test
POPS GF@tmpPrint
WRITE GF@tmpPrint
LABEL ower%2
POPFRAME